'use client';
import { useState } from 'react';
import { FileSpreadsheet, Loader2, ShieldAlert } from 'lucide-react';

type Risk = { studentId:string; name:string; rollNumber:string; class:string; section:string; percentage:number; riskLevel:string; attended:number; totalHeld:number; guardianPhone?:string };
export default function ReportsPage(){
 const [items,setItems]=useState<Risk[]>([]); const [loading,setLoading]=useState(false); const [cls,setCls]=useState(''); const [section,setSection]=useState('');
 async function load(){setLoading(true); const p=new URLSearchParams(); if(cls)p.set('class',cls); if(section)p.set('section',section); const res=await fetch(`/api/reports/non-collegiate?${p}`); const data=await res.json(); setItems(data.students||[]); setLoading(false)}
 return <div><div className="mb-6"><h1 className="m-0 text-2xl font-black text-slate-900">Reports</h1><p className="mt-1 text-sm text-slate-500">Generate daily, monthly, class-wise and non-collegiate reports.</p></div><div className="card mb-4 flex flex-wrap gap-3 p-4"><select className="input max-w-[170px]" value={cls} onChange={(e)=>setCls(e.target.value)}><option value="">All Classes</option>{['6','7','8','9','10','11','12'].map(c=><option key={c} value={c}>Class {c}</option>)}</select><select className="input max-w-[170px]" value={section} onChange={(e)=>setSection(e.target.value)}><option value="">All Sections</option>{['A','B','C','D'].map(s=><option key={s} value={s}>Section {s}</option>)}</select><button onClick={load} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">{loading?<Loader2 className="animate-spin" size={16}/>:<ShieldAlert size={16}/>}Non-Collegiate</button><a href="/api/reports/attendance/export?type=xlsx" className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-700"><FileSpreadsheet size={16}/>Export Excel</a><a href="/api/reports/attendance/export?type=csv" className="inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50 px-4 py-2 text-sm font-bold text-blue-700"><FileSpreadsheet size={16}/>Export CSV</a></div><div className="card overflow-hidden"><div className="border-b bg-slate-50 px-5 py-4 font-black">Risk / Non-Collegiate Students</div>{loading?<div className="p-10"><Loader2 className="animate-spin"/></div>:items.length===0?<div className="p-10 text-center text-slate-500">No risk students loaded. Click Non-Collegiate.</div>:<table><thead><tr><th>Student</th><th>ID</th><th>Class</th><th>Attendance</th><th>Risk</th><th>Guardian</th></tr></thead><tbody>{items.map(i=><tr key={i.studentId}><td className="font-bold">{i.name}</td><td>{i.studentId}</td><td>{i.class}-{i.section}</td><td>{i.percentage}% ({i.attended}/{i.totalHeld})</td><td><span className="badge badge-danger">{i.riskLevel}</span></td><td>{i.guardianPhone||'—'}</td></tr>)}</tbody></table>}</div></div>
}
